#!/usr/bin/env python3
"""
Generate src/buda-tables.js from BUDA's py-tiblegenc font tables.

py-tiblegenc (https://github.com/buda-base/py-tiblegenc) ships authoritative,
reviewed legacy-encoding tables for ~194 Tibetan fonts (TibetanChogyal,
TibetanMachine(Web), Esams, Ededris, Dzongkha, Classic, …). Each row is:

    FontPostScriptName,decimalCodepoint,unicodeString

where decimalCodepoint is the code point of the character as the legacy text was
decoded (so the table is keyed by the character a parser actually sees), and the
unicode string is the atomic Tibetan piece. Per-run conversion concatenates
these pieces (validated end-to-end against the Swift Path document at 99.95%).

Usage:
    pip install "git+https://github.com/buda-base/py-tiblegenc"
    python scripts/import-buda-tables.py            # writes src/buda-tables.js

This is the single source of truth — re-run it to pick up upstream fixes.
"""
import os, csv, glob, json, sys

# Conflict priority: tiblegenc (PKTC / Padmakara-reviewed) wins, then UTFC, UDP, ATTU.
PRIORITY = ["tiblegenc.csv", "utfc.csv", "udp.csv", "attu.csv"]


def find_tables_dir():
    try:
        import pytiblegenc
        d = os.path.join(os.path.dirname(pytiblegenc.__file__), "font-tables")
        if os.path.isdir(d):
            return d
    except Exception:
        pass
    if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]):
        return sys.argv[1]
    sys.exit("Could not find py-tiblegenc font-tables. Install it or pass the dir as arg.")


def main():
    d = find_tables_dir()
    tables = {}
    conflicts = 0
    for base in PRIORITY:
        fn = os.path.join(d, base)
        if not os.path.exists(fn):
            continue
        with open(fn, encoding="utf-8") as f:
            for row in csv.reader(f):
                if len(row) < 3:
                    continue
                font, cp, uni = row[0], row[1], row[2]
                try:
                    cp = int(cp)
                except ValueError:
                    continue
                font_tab = tables.setdefault(font, {})
                if cp in font_tab:
                    if font_tab[cp] != uni:
                        conflicts += 1
                    continue
                font_tab[cp] = uni
    out = {font: {str(cp): uni for cp, uni in t.items()} for font, t in tables.items()}
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dest = os.path.join(here, "src", "buda-tables.js")
    payload = json.dumps(out, ensure_ascii=False, separators=(",", ":"))
    with open(dest, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/import-buda-tables.py — do not edit by hand.\n")
        f.write("// Data derived from BUDA py-tiblegenc font tables, Apache License 2.0.\n")
        f.write("// Source: https://github.com/buda-base/py-tiblegenc (font-tables)\n")
        f.write("// See THIRD_PARTY_NOTICES.md and LICENSES/py-tiblegenc-Apache-2.0.txt\n")
        f.write("// { fontPostScriptName: { decimalCodepoint: unicodeString } }\n")
        f.write("export default " + payload + ";\n")
    print(f"fonts: {len(out)}  conflicts skipped: {conflicts}")
    print(f"wrote {dest} ({os.path.getsize(dest)} bytes)")


if __name__ == "__main__":
    main()
