// Font registry for font-aware conversion, backed by BUDA's authoritative
// legacy-encoding tables (see src/buda-tables.js, generated by
// scripts/import-buda-tables.py from https://github.com/buda-base/py-tiblegenc).
//
// Legacy Tibetan fonts reuse the same code points for different glyphs, so a
// byte can only be resolved correctly if we know which font the run was set in.
// Each table maps decimalCodepoint -> atomic Unicode piece; converting a run is
// a direct per-character lookup, and concatenation rebuilds stacked clusters
// (validated end-to-end against a real pecha at 99.95%).

import budaTables from "./buda-tables.js";

// Normalize a font name from .docx (w:rFonts) / .rtf (\fonttbl) / HTML
// (font-family) / PDF (subset prefix) to match a table key.
export function normalizeFontName(name) {
  if (!name) return "";
  let n = String(name).split(",")[0].trim();
  n = n.replace(/^[A-Z]{6}\+/, ""); // PDF/embedded subset prefix e.g. "ABCDEF+"
  n = n.replace(/['"]/g, "");
  n = n.toLowerCase();
  n = n.replace(/\b(regular|bold|italic|oblique|medium|light)\b/g, "");
  n = n.replace(/[\s_-]+/g, "");
  return n;
}

// Index every BUDA font under its normalized name.
const byNorm = {};
for (const name of Object.keys(budaTables)) {
  byNorm[normalizeFontName(name)] = budaTables[name];
}

// Return the codepoint->unicode table for a font, or null if unknown.
export function getBudaTable(fontName) {
  return byNorm[normalizeFontName(fontName)] || null;
}

export function isKnownFont(fontName) {
  return getBudaTable(fontName) != null;
}

// Sorted list of supported font PostScript names.
export const supportedFonts = Object.keys(budaTables).sort();

// Unicode Tibetan fonts render at different visual sizes than the legacy fonts
// for the same point size, so when re-fonting a document we scale the point
// sizes to keep the original visual size. Anchored on Jomolhari ≈ 0.72 of the
// legacy size; others derived from their KA/em ratio. Tweakable.
const SIZE_SCALE = {
  jomolhari: 0.72,
  tibetanmachineuni: 1.17,
  tibetanmachineunicode: 1.17,
  ddcuchen: 0.59,
};
export function defaultSizeScale(fontName) {
  return SIZE_SCALE[normalizeFontName(fontName)] ?? 1;
}
